version: '3'

tasks:
  test:
    desc: Run all Terratest cases
    cmds:
      - go test ./test/...
    env:
      GITHUB_TOKEN: $GITHUB_TOKEN
  fmt:
    cmds:
      - terraform fmt -recursive
  husky:
    desc: Setup Git hooks for local dev
    cmds:
      - npx husky install