name: Build

# Minimal permissions for security hardening
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    # Specific permissions needed for SonarCloud analysis
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.21'
          cache: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: latest
      
      - name: Run Go tests with coverage
        run: |
          export GO111MODULE=on
          go mod tidy
          # Run template rendering tests that don't require external dependencies
          go test -coverprofile=coverage.out -run "TestPrintWorkingDirectory|TestRenderDependabotTemplate|TestRenderCodeQLTemplate|TestRenderCIEnforcementTemplate" ./test
          go tool cover -func=coverage.out > coverage.txt
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set SonarCloud environment
        run: echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> $GITHUB_ENV
        
      - name: Check SonarCloud Configuration
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "::notice title=SonarCloud::SONAR_TOKEN not configured - skipping SonarCloud analysis"
            echo "To enable SonarCloud analysis, configure SONAR_TOKEN as a repository secret"
          else
            echo "::notice title=SonarCloud::SONAR_TOKEN configured - running SonarCloud analysis"
          fi

      - name: SonarCloud Scan
        if: env.SONAR_TOKEN != ''
        uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8 # v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}