name: "CI"

on:
  pull_request:
    paths:
      - '**/*.tf'
      - 'README.md'
      - 'Taskfile.yml'
      - '.terraform-docs.yml'
      - 'policy/**'

jobs:
  terraform:
    name: "Terraform Validation"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: ["1.5.0", "1.6.0"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        run: terraform plan -input=false

      - name: Terraform plan (JSON)
        run: terraform plan -input=false -refresh=false -out=tfplan.binary && terraform show -json tfplan.binary > ci-tfplan.json

      - name: Install conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.51.0/conftest_0.51.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.51.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run OPA guardrails (conftest)
        run: conftest test --policy policy/ ci-tfplan.json
      - name: Install OPA
        run: |
          wget https://github.com/open-policy-agent/opa/releases/download/v1.5.1/opa_linux_amd64 -O opa
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Lint OPA policies
        run: opa fmt -w policy/ && opa lint policy/

      - name: Check for drift (no unexpected resource changes)
        run: bash scripts/ci-check-drift.sh

      - name: Run TFLint
        run: tflint

      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Trivy and output to console
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'

      - name: Update Terraform docs
        run: terraform-docs . --output-file README.md --output-mode inject

      - name: Setup Node.js for Markdown lint
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdownlint CLI
        run: npm install -g markdownlint-cli2

      - name: Lint Markdown files
        run: markdownlint-cli2 "**/*.md"

      - name: Commit updated docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update Terraform docs [skip ci]"
          file_pattern: README.md

  test:
    name: Terratest
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run Terratest suite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go test ./test/... -timeout 5m
