name: "CI"

on:
  pull_request:
    paths:
      - '**/*.tf'
      - 'README.md'
      - 'Taskfile.yml'
      - '.terraform-docs.yml'

jobs:
  terraform:
    name: "Terraform Validation"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: ["1.5.0", "1.6.0"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        run: terraform plan -input=false

      - name: Terraform plan (JSON)
        run: terraform plan -input=false -refresh=false -out=tfplan.binary && terraform show -json tfplan.binary > ci-tfplan.json

      - name: Check for drift (no unexpected resource changes)
        run: bash scripts/ci-check-drift.sh

      - name: Run TFLint
        run: tflint

      - name: Run tfsec
        run: tfsec --format github

      - name: Update Terraform docs
        run: terraform-docs . --output-file README.md --output-mode inject

      - name: Setup Node.js for Markdown lint
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdownlint CLI
        run: npm install -g markdownlint-cli2

      - name: Lint Markdown files
        run: markdownlint-cli2 "**/*.md"

      - name: Commit updated docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update Terraform docs [skip ci]"
          file_pattern: README.md

  test:
    name: Terratest
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run Terratest suite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go test ./test/... -timeout 5m
