name: "CI"

on:
  pull_request:
    paths:
      - '**/*.tf'
      - 'README.md'
      - 'Taskfile.yml'
      - '.terraform-docs.yml'
      - 'policy/**'

# Least-privilege permissions for the entire workflow
permissions:
  contents: read          # Read repository contents
  security-events: write  # Upload SARIF security results
  pull-requests: write    # Comment on PRs and auto-commit
  actions: read          # Read workflow information

jobs:
  terraform:
    name: "Terraform Validation"
    runs-on: ubuntu-latest
    
    # Job-specific permissions (most restrictive)
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    
    strategy:
      matrix:
        terraform_version: ["1.5.0", "1.6.0"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        run: terraform plan -input=false

      - name: Terraform plan (JSON)
        run: terraform plan -input=false -refresh=false -out=tfplan.binary && terraform show -json tfplan.binary > ci-tfplan.json

      - name: Install conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.51.0/conftest_0.51.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.51.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run OPA guardrails (conftest)
        run: conftest test --policy policy/ ci-tfplan.json
      - name: Install OPA
        run: |
          wget https://github.com/open-policy-agent/opa/releases/download/v1.5.1/opa_linux_amd64 -O opa
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Lint OPA policies
        run: opa fmt -w policy/ && opa lint policy/

      - name: Check for drift (no unexpected resource changes)
        run: bash scripts/ci-check-drift.sh

      - name: Run TFLint
        run: tflint

      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@76071ef0d7ec797419534a183b498b4d6366cf37 # master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3.29.0
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Trivy and output to console
        uses: aquasecurity/trivy-action@76071ef0d7ec797419534a183b498b4d6366cf37 # master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'

      - name: Update Terraform docs
        run: terraform-docs . --output-file README.md --output-mode inject

      - name: Setup Node.js for Markdown lint
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '18'

      - name: Install markdownlint CLI
        run: npm install -g markdownlint-cli2

      - name: Lint Markdown files
        run: markdownlint-cli2 "**/*.md"

      - name: Commit updated docs
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v4.16.0
        with:
          commit_message: "chore: update Terraform docs [skip ci]"
          file_pattern: README.md

  test:
    name: Terratest
    runs-on: ubuntu-latest
    needs: terraform
    
    # Job-specific permissions
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.21'

      - name: Run Terratest suite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go test ./test -timeout 5m
