name: Deploy Documentation

# Description: This workflow builds and deploys documentation to GitHub Pages.
# It runs on main branch pushes, documentation-related PRs, releases, and manual triggers.
# - PR events: Updates docs in the PR branch
# - Main/release events: Deploys docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '*.tf'
      - 'examples/**'
      - 'README.md'
  pull_request:
    paths:
      - 'variables.tf'
      - 'outputs.tf'
      - 'README.md'
      - 'docs/**'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  update-terraform-docs:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/reusable-terraform-docs.yml
    permissions:
      contents: write
    with:
      working_directory: "."
      output_file: "README.md"
      git_push: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy-docs:
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    runs-on: ubuntu-latest
    # Set explicit permissions for the build-and-deploy-docs job
    permissions:
      contents: write  # For git push operations
      pages: write     # For GitHub Pages configuration
      id-token: write  # For deployment authentication
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0  # Needed for git-revision-date-localized plugin
          # Set token for proper permissions for gh-pages branch operations
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install OpenSSL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev openssl ca-certificates

      - name: Install MkDocs dependencies
        run: |
          # Upgrade pip first
          python -m pip install --upgrade pip setuptools wheel
          
          # Clear pip cache to ensure clean environment
          pip cache purge
          
          # Install with certificate verification configured during build
          export PYTHONHTTPSVERIFY=0
          export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
          export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
          
          # Install critical dependencies first with specific versions
          pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --no-cache-dir pyyaml==6.0.1 mergedeep==1.3.4 markupsafe==2.1.3 jinja2==3.1.2 packaging==23.2
          
          # Wait a moment to ensure dependencies are properly registered
          sleep 2
          
          # Install requirements from file with SSL handling
          pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --no-cache-dir -r docs/requirements.txt
          
          # Ensure core dependencies are installed, even if requirements.txt changes
          pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --no-cache-dir --no-deps mike==2.0.0
          
          # Show detailed dependency information for debugging
          echo "Key package versions:"
          pip list | grep -E "mergedeep|pyyaml|mkdocs|mike|jinja2|markupsafe"
          
          # List all installed packages for debugging
          echo "All installed packages:"
          pip list

      - name: Apply Python SSL fixes
        run: |
          source ./scripts/fix-python-ssl.sh

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: latest

      - name: Generate API Documentation
        run: |
          # Install terraform-docs
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.17.0/terraform-docs-v0.17.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          
          # Create API docs directory if it doesn't exist
          mkdir -p docs/api
          
          # Generate comprehensive API documentation
          echo "# Inputs" > docs/api/inputs.md
          echo "" >> docs/api/inputs.md
          echo "This page documents all available input variables for the module." >> docs/api/inputs.md
          echo "" >> docs/api/inputs.md
          ./terraform-docs markdown table --output-template '{{ .Inputs }}' . >> docs/api/inputs.md
          
          echo "# Outputs" > docs/api/outputs.md  
          echo "" >> docs/api/outputs.md
          echo "This page documents all outputs provided by the module." >> docs/api/outputs.md
          echo "" >> docs/api/outputs.md
          ./terraform-docs markdown table --output-template '{{ .Outputs }}' . >> docs/api/outputs.md
          
          echo "# Resources" > docs/api/resources.md
          echo "" >> docs/api/resources.md
          echo "This page documents all resources created by the module." >> docs/api/resources.md
          echo "" >> docs/api/resources.md
          ./terraform-docs markdown table --output-template '{{ .Resources }}' . >> docs/api/resources.md
          
          # Generate example documentation
          mkdir -p docs/examples
          for example in examples/*/; do
            if [ -d "$example" ]; then
              example_name=$(basename "$example")
              echo "# ${example_name^} Example" > "docs/examples/${example_name}.md"
              echo "" >> "docs/examples/${example_name}.md"
              if [ -f "${example}/README.md" ]; then
                cat "${example}/README.md" >> "docs/examples/${example_name}.md"
              else
                echo "Example configuration for ${example_name}." >> "docs/examples/${example_name}.md"
                echo "" >> "docs/examples/${example_name}.md"
                echo '```hcl' >> "docs/examples/${example_name}.md"
                cat "${example}/main.tf" >> "docs/examples/${example_name}.md" 2>/dev/null || echo "# Example configuration" >> "docs/examples/${example_name}.md"
                echo '```' >> "docs/examples/${example_name}.md"
              fi
            fi
          done

      # We've moved the git config into the build and deploy step

      - name: Get version info
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            VERSION="${{ github.event.release.tag_name }}"
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            VERSION="latest"
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
        with:
          enablement: true
          
      - name: Verify Pages Setup
        run: |
          if [[ -z "${{ steps.pages.outputs }}" ]]; then
            echo "::notice::GitHub Pages setup completed but didn't return output. This is normal for private repositories."
          else
            echo "GitHub Pages setup completed successfully."
          fi

      - name: Fix Mike Alias Conflicts
        run: |
          # Run the fix-mike-aliases script to clean up any alias conflicts
          chmod +x ./scripts/fix-mike-aliases.sh
          ./scripts/fix-mike-aliases.sh

      - name: Fix Mike alias conflicts
        run: |
          # Run the fix-mike-aliases script to clean up any alias conflicts before deployment
          chmod +x ./scripts/fix-mike-aliases.sh
          ./scripts/fix-mike-aliases.sh

      - name: Build and deploy with versioning
        run: |
          # Set environment variables for Python SSL
          export PYTHONHTTPSVERIFY=0
          export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
          export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
          
          # Validate mkdocs configuration with error handling
          echo "Validating mkdocs configuration..."
          if ! mkdocs build --clean --strict; then
            echo "::warning::MkDocs build failed with strict mode, trying with verbose output"
            if ! mkdocs build --verbose; then
              echo "::error::MkDocs build failed! Checking Python environment..."
              python -c "import sys; print(sys.path)"
              python -c "import yaml, mergedeep; print('YAML version:', yaml.__version__, 'Mergedeep version:', mergedeep.__version__)"
              exit 1
            fi
          fi
          
          # Verify site directory was created and has content
          if [ ! -d "site" ] || [ -z "$(ls -A site 2>/dev/null)" ]; then
            echo "::error::Site directory is missing or empty after build!"
            exit 1
          else
            echo "Site directory created successfully with $(find site -type f | wc -l) files"
          fi
          
          # Configure Git for GitHub Pages deployment
          echo "Setting up Git configuration for branch management..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Commit any generated API documentation files to avoid conflicts
          git add docs/api/ docs/examples/ || true
          git diff-index --quiet HEAD || git commit -m "chore: update generated documentation [skip ci]" || true
          
          # Make sure our main branch is clean and up to date
          git checkout main -f
          git pull origin main
          
          # Clean up any previous mike state to avoid conflicts
          rm -rf .mike 2>/dev/null || true
          
          if [[ "${{ steps.version.outputs.is_release }}" == "true" ]]; then
            # For releases, create a versioned deployment
            echo "Deploying versioned documentation for release ${{ steps.version.outputs.version }}..."
            
            # Step 1: First deploy only the version without any aliases
            echo "Step 1: Deploying version ${{ steps.version.outputs.version }} (no aliases)..."
            mike deploy --push ${{ steps.version.outputs.version }} --title "${{ steps.version.outputs.version }}"
            
            # Wait to ensure changes are registered
            sleep 5
            
            # Step 2: Only after successful version deployment, create the alias separately
            echo "Step 2: Setting version ${{ steps.version.outputs.version }} as 'latest' alias..."
            mike alias --push --update ${{ steps.version.outputs.version }} latest
          else
            # For main branch, update latest documentation
            echo "Deploying latest documentation from main branch..."
            
            # Step 1: First delete any existing 'latest' version if it exists
            mike delete latest --push || echo "No latest version to delete, continuing..."
            
            # Wait to ensure changes are registered
            sleep 2
            
            # Step 2: Deploy 'latest' version without any aliases
            mike deploy --push latest --title "Latest (main)"
          fi
          
          # Wait again before setting default
          sleep 5
          
          # Step 3: Always set 'latest' as the default version
          echo "Setting 'latest' as the default version..."
          mike set-default --push latest
          
          # Verify deployment structure
          echo "Deployment complete. Running verification..."
          
          # Get current branch
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          # Check the gh-pages branch structure if possible
          if git fetch origin gh-pages && git checkout gh-pages; then
            echo "✅ gh-pages branch exists and is accessible"
            if [ -f ".mike" ]; then
              echo "✅ .mike file exists with the following content:"
              cat .mike
            else
              echo "⚠️ .mike file does not exist!"
            fi
            
            # Return to original branch
            git checkout $CURRENT_BRANCH
          else
            echo "⚠️ Could not access gh-pages branch for verification"
          fi
        env:
          # Increase Python's error verbosity
          PYTHONVERBOSE: 1
          # GitHub token for git operations and plugins
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GitHub token for git-committers plugin (MKDOCS_GIT_COMMITTERS_APIKEY is what the plugin looks for)
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GIT_COMMITTERS_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: site

  deploy:
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: build-and-deploy-docs
    # Set required permissions for GitHub Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment source
    # Deploy to the GitHub Pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5