name: Reusable Security Scanning

# Description: This is a reusable workflow for security scanning with Trivy
# It can be called by other workflows to provide standardized security scanning

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Directory to scan'
        type: string
        default: '.'
      target_type:
        description: 'Type of target to scan (fs, repo, image)'
        type: string
        default: 'fs'
      format:
        description: 'Output format (sarif, json, table)'
        type: string
        default: 'sarif'
      severity:
        description: 'Severities to filter (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)'
        type: string
        default: 'MEDIUM,HIGH,CRITICAL'
      upload_to_security_tab:
        description: 'Whether to upload results to GitHub Security tab'
        type: boolean
        default: true

jobs:
  security-scan:
    name: "Security Scan"
    runs-on: ubuntu-latest
    
    # Least-privilege permissions for the job
    permissions:
      contents: read
      security-events: write  # Needed to upload SARIF results
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # v0.18.0
        with:
          scan-type: ${{ inputs.target_type }}
          scan-ref: ${{ inputs.working_directory }}
          format: ${{ inputs.format }}
          output: 'trivy-results.${{ inputs.format }}'
          severity: ${{ inputs.severity }}
          exit-code: '1'
          ignore-unfixed: true
      
      - name: Upload Trivy scan results to GitHub Security tab
        if: inputs.upload_to_security_tab == true && inputs.format == 'sarif'
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 # v3.29.0
        with:
          sarif_file: 'trivy-results.sarif'
      
      - name: Upload scan results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.*
          retention-days: 5
