name: Go Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.22'

      - name: Run tests with coverage
        run: go test -cover -coverprofile=coverage.out ./...

      - name: Generate coverage report
        uses: gwatts/go-coverage-action@v2
        with:
          coverage-threshold: 80
          cover-pkg: ./...
          ignore-pattern: |
            \.pb\.go$
            \_string\.go$