name: "Traceability Check"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  traceability:
    runs-on: ubuntu-latest
    steps:
      - name: "Check PR references and issue state"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || "";
            const issueRefRegex = /#(\d+)/g;
            const matches = [...body.matchAll(issueRefRegex)];

            if (matches.length === 0) {
              core.setFailed("PR must reference at least one issue using #<number>.");
              return;
            }

            const issueNumber = matches[0][1]; // just check the first one
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });

            if (!issue.data.assignee) {
              core.setFailed(`Referenced issue #${issueNumber} has no assignee.`);
              return;
            }

            const acceptableStates = ["in progress", "active", "doing"];
            const labels = issue.data.labels.map(label => label.name.toLowerCase());
            const validState = labels.some(label => acceptableStates.includes(label));

            if (!validState) {
              core.setFailed(`Referenced issue #${issueNumber} must have one of these labels: ${acceptableStates.join(", ")}`);
            }
